# Generated by Django 4.2 on 2024-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_remove_client_city_remove_client_manager_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deal',
        ),
        migrations.AddField(
            model_name='client',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='surname',
            field=models.CharField(default='неизвестно', max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default='example@example.com', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('employee', 'Сотрудник')], default='раб', max_length=10),
        ),
    ]
