# Generated by Django 4.2 on 2025-01-24 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_user_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='client',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(default='Ваш уникальный логин', max_length=150),
        ),
    ]
